# Description: This file is used to define the deployment manifest for your application.
# Remind to update the env_id and app_id with your target env and app id

name: NX1 Deploy a Static Service (my-simple-react-app)

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  deployments: write

jobs:
  my-simple-react-app:
    runs-on: ubuntu-latest
    name: NX1 Action
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run build

      - name: NX1 Prepare Deployment
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'prepare'
          env_id: '6a5f5001-2732-4670-a46c-7a97813d0ebc' # @TODO: update with your target NX1 env id
          app_id: '9b0b7b69-2e42-436b-ab81-98cebf72bd39' # @TODO: update with your NX1 app id
          api_token: ${{ secrets.APP_TOKEN }}

      - name: NX1 Assume Role
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'assume-role'

      - name: NX1 Deploy Static Service
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'deploy'
          service: 'my-simple-react-app' # @TODO: update with your NX1 service nam
