---

name: NX1 Deploy
run-name: Deploy app-nonprod to nonprod-self-contained-ohio (us-east-2/852718040374) by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: NX1 Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - run: npm ci
      - run: npm run build

      - name: NX1 Prepare Deployment
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'prepare'
          app_id: 9b20993f-79df-4984-b1f1-756a929638ed
          api_url: 'https://dev-app.citadel.run/api'
          api_token: ${{ secrets.EXAMPLE_REACT_JS }}
          env_id: c0b2b5f6-83df-4926-8ab4-8ee1dfaff869

      - name: NX1 Assume Role
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'assume-role'

      - name: NX1 Deploy Service - static-react
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'deploy'
          service: 'static-react'

      # Optional step: Migrate database
      # - name: NX1 Migrate Service - static-react
      #   uses: nx1-io/app-copilot-action@main
      #   with:
      #     operation: 'run'
      #     service: 'static-react'
      #     command: 'uname -a' # replace with your migration command


# rev:1
