---

name: NX1 Deploy
run-name: Deploy app-xpta to nonprod-self-contained-ohio (us-east-2/852718040374) by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: NX1 Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional step: Detect app and construct Dockerfile using Nixpacks
      - name: NX1 Build with Nixpacks
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'build-nixpacks'

      - name: NX1 Prepare Deployment
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'prepare'
          app_id: 9b027592-4888-4a08-9a46-63ad79ab14d5
          api_url: 'https://dev-app.citadel.run/api'
          api_token: ${{ secrets.EXAMPLE_REACT_JS }}
          env_id: c0b2b5f6-83df-4926-8ab4-8ee1dfaff869

      - name: NX1 Assume Role
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'assume-role'

      - name: NX1 Deploy Service - test-static
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'deploy'
          service: 'test-static'

      # Optional step: Migrate database
      - name: NX1 Migrate Service - test-static
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'run'
          service: 'test-static'
          command: 'uname -a' # replace with your migration command


# rev:1
